-- 014_add_report_tokens.sql
-- Unguessable public report URLs. Mission reports were previously exposed at
-- /report/:planId where planId is a monotonically increasing integer — an
-- enumerable identifier that would let anyone iterate other customers'
-- full deal/strategy reports. This migration backfills a random 192-bit
-- report_token for every existing plan and makes it unique; new plans get a
-- token generated by db/repos.js at creation. Forward-only and idempotent.
-- Requires Postgres 13+ (gen_random_uuid() is built in, no extension).

ALTER TABLE plans ADD COLUMN IF NOT EXISTS report_token VARCHAR(64);

UPDATE plans
SET report_token = left(replace(gen_random_uuid()::text, '-', ''), 32)
WHERE report_token IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_plans_report_token ON plans(report_token);