// EU AI Act transparency enforcement (Regulation (EU) 2024/1689, Art. 50).
//
// Transparency obligations are first-class design constraints. The EU AI Act
// transparency rules apply from 2 August 2026. This module is the single
// source of truth for the markers the system attaches before any content is
// exposed to a natural person:
//
//   Art. 50(1) — interactive AI systems must identify themselves as AI.
//     Enforced by bot/index.js: every message the assistant sends carries
//     withAiDisclosure().
//
//   Art. 50(2) — AI-generated content must be marked in a machine-readable
//     format and detectable as artificially generated or manipulated.
//     Enforced by services/outboundWorker/index.js: every email that leaves
//     the perimeter carries withContentMarking().
//
// The marker is appended in the send path, so no message or email can leave
// the system without it (idempotent: re-applying never duplicates the mark).
'use strict';

const AI_DISCLOSURE_EN = '🤖 This message was generated by an AI assistant.';
const AI_DISCLOSURE_AR = '🤖 هذه الرسالة من إعداد مساعد ذكاء اصطناعي.';

const AI_CONTENT_MARKER = 'AI-CONTENT-MARKER: AI-Generated Content';
const AI_CONTENT_DISCLOSURE_EN = 'This email was generated by an AI workforce on behalf of Elmahrosa International. It is marked as AI-generated content under the EU AI Act (Regulation (EU) 2024/1689), Article 50(2).';

const DISCLOSURES = Object.freeze({ en: AI_DISCLOSURE_EN, ar: AI_DISCLOSURE_AR });

function hasAiDisclosure(text, lang) {
  const disclosure = DISCLOSURES[lang] || AI_DISCLOSURE_EN;
  return String(text || '').indexOf(disclosure) !== -1;
}

function withAiDisclosure(text, lang) {
  const body = String(text == null ? '' : text);
  const footer = DISCLOSURES[lang] || AI_DISCLOSURE_EN;
  if (hasAiDisclosure(body, lang)) return body;
  const trimmed = body.trim();
  return trimmed.length ? `${trimmed}\n\n${footer}` : footer;
}

function hasContentMarking(text) {
  return String(text || '').indexOf(AI_CONTENT_MARKER) !== -1;
}

function withContentMarking(text) {
  const body = String(text == null ? '' : text);
  if (hasContentMarking(body)) return body;
  const trimmed = body.trim();
  const footer = `---\n${AI_CONTENT_MARKER}\n${AI_CONTENT_DISCLOSURE_EN}`;
  return trimmed.length ? `${trimmed}\n\n${footer}` : footer;
}

module.exports = {
  AI_DISCLOSURE_EN,
  AI_DISCLOSURE_AR,
  AI_CONTENT_MARKER,
  AI_CONTENT_DISCLOSURE_EN,
  DISCLOSURES,
  hasAiDisclosure,
  withAiDisclosure,
  hasContentMarking,
  withContentMarking
};
